name: Release Drafter

on:
  push:
    branches:
      - master
      - test-release-drafter
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  update_release_draft:
    runs-on: ubuntu-20.04
    steps:
      - uses: MariuszKogut/release-drafter@Fix824
        with:
          commitish: refs/heads/master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
